### ISSUE TITLE
Logout, then login fails

### ISSUE THREAD

**Issue by haileycorbett** [slickqa/slickqaweb#8]
Logout, then logging back in causes an error.  This is what's on the console of the server:
Generated checkid_setup request to https://www.google.com/accounts/o8/ud with assocication 1.AMlYA9XOKqSrNsO5HeCH1ut7IrGXixX4o43beyytMuIVbJXi7DmEENlz3e-eyQ
Error attempting to use stored discovery information: <openid.consumer.consumer.TypeURIMismatch: Required type http://specs.openid.net/auth/2.0/signon not found in ['http://specs.openid.net/auth/2.0/server', 'http://openid.net/srv/ax/1.0', 'http://specs.openid.net/extensions/ui/1.0/mode/popup', 'http://specs.openid.net/extensions/ui/1.0/icon', 'http://specs.openid.net/extensions/pape/1.0'] for endpoint <openid.consumer.discover.OpenIDServiceEndpoint server_url='https://www.google.com/accounts/o8/ud' claimed_id=None local_id=None canonicalID=None used_yadis=True >>
Attempting discovery to verify endpoint
Performing discovery on https://www.google.com/accounts/o8/id?id=AItOawn5L39wFXvQAST0J3bUzGYpTUXNI1lq29A
Received id_res response from https://www.google.com/accounts/o8/ud using association 1.AMlYA9XOKqSrNsO5HeCH1ut7IrGXixX4o43beyytMuIVbJXi7DmEENlz3e-eyQ
[13/Mar/2014:15:18:15] ENGINE AssertionError()
Traceback (most recent call last):
  File "/Users/jcorbett/Development/slick/3.0.0.0.0/vpy/lib/python2.7/site-packages/cherrypy/wsgiserver/wsgiserver2.py", line 1302, in communicate
    req.respond()
  File "/Users/jcorbett/Development/slick/3.0.0.0.0/vpy/lib/python2.7/site-packages/cherrypy/wsgiserver/wsgiserver2.py", line 831, in respond
    self.server.gateway(self).respond()
  File "/Users/jcorbett/Development/slick/3.0.0.0.0/vpy/lib/python2.7/site-packages/cherrypy/wsgiserver/wsgiserver2.py", line 2135, in respond
    response = self.req.server.wsgi_app(self.env, self.start_response)
  File "/Users/jcorbett/Development/slick/3.0.0.0.0/vpy/lib/python2.7/site-packages/cherrypy/_cptree.py", line 290, in __call__
    return app(environ, start_response)
  File "/Users/jcorbett/Development/slick/3.0.0.0.0/vpy/lib/python2.7/site-packages/flask/app.py", line 1836, in **call**
    return self.wsgi_app(environ, start_response)
  File "/Users/jcorbett/Development/slick/3.0.0.0.0/vpy/lib/python2.7/site-packages/flask/app.py", line 1820, in wsgi_app
    response = self.make_response(self.handle_exception(e))
  File "/Users/jcorbett/Development/slick/3.0.0.0.0/vpy/lib/python2.7/site-packages/flask/app.py", line 1403, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/jcorbett/Development/slick/3.0.0.0.0/vpy/lib/python2.7/site-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/jcorbett/Development/slick/3.0.0.0.0/vpy/lib/python2.7/site-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/jcorbett/Development/slick/3.0.0.0.0/vpy/lib/python2.7/site-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/jcorbett/Development/slick/3.0.0.0.0/vpy/lib/python2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/jcorbett/Development/slick/3.0.0.0.0/vpy/lib/python2.7/site-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/jcorbett/Development/slick/3.0.0.0.0/slickqaweb/api/testrungroup.py", line 17, in get_testrungroups
    return JsonResponse(queryFor(TestrunGroup))
  File "/Users/jcorbett/Development/slick/3.0.0.0.0/slickqaweb/api/standardResponses.py", line 11, in JsonResponse
    return Response(dumps(serialize_this(obj)),
  File "/Users/jcorbett/Development/slick/3.0.0.0.0/slickqaweb/model/serialize.py", line 37, in document_to_plain
    return [document_to_plain(item) for item in doc]
  File "/Users/jcorbett/Development/slick/3.0.0.0.0/slickqaweb/model/serialize.py", line 27, in document_to_plain
    for key, value in doc.dynamic_fields().items():
  File "/Users/jcorbett/Development/slick/3.0.0.0.0/slickqaweb/model/testrunGroup.py", line 16, in dynamic_fields
    'state': self.state(),
  File "/Users/jcorbett/Development/slick/3.0.0.0.0/slickqaweb/model/testrunGroup.py", line 25, in state
    assert isinstance(testrun, Testrun)
AssertionError

**Comment by stevejensen22** [comment]
Not tackling login anymore on slickv1
